language: ruby
dist: bionic
cache: bundler
rvm:
  - 2.6.5
addons:
  apt:
    packages:
    - slapd
    - ldap-utils
    - unixodbc-dev
  postgresql: 11
services:
  - postgresql
stages:
  - build
  - test
env:
  - ENABLE_WEB_CONSOLE='true'
  - ENABLE_WEB_CONSOLE='false'
before_script:
  - 'cp config/application.travis.yml config/application.yml'
  - 'bundle exec rails db:create db:migrate'
  - 'slapd -f test/fixtures/ldap/slapd.conf -h ldap://localhost:3389'
  - 'bundle exec rails ldap:reset'
install:
  - 'rm ${BUNDLE_GEMFILE}.lock'
  - 'eval bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-$PWD/vendor/bundle}'

jobs:
  include:
    - stage: build
      script: docker build -t gredit/app .
      install: skip
      before_script: cp config/application.travis.yml config/application.yml
      env:
      rvm:
      addons:
        apt:
          packages:
            - docker-ce
      services:
        - docker
