language: ruby
dist: xenial
cache: bundler
sudo: false
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
addons:
  apt:
    packages:
    - slapd
    - ldap-utils
    - unixodbc-dev
  postgresql: 10
services:
  - postgresql
env:
  - ENABLE_WEB_CONSOLE='true'
  - ENABLE_WEB_CONSOLE='false'
before_install:
  - 'gem install bundler'
before_script:
  - 'cp config/application.travis.yml config/application.yml'
  - "psql -c 'create database monitor_test;' -U postgres"
  - 'bundle exec rake db:migrate'
  - 'slapd -f test/fixtures/ldap/slapd.conf -h ldap://localhost:3389'
  - 'bundle exec rake ldap:reset'
install:
  - 'rm ${BUNDLE_GEMFILE}.lock'
  - 'eval bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}'
