language: ruby
dist: xenial
sudo: false
rvm:
  - 2.5.5
  - 2.6.3
addons:
  apt:
    packages:
    - slapd
    - ldap-utils
    - unixodbc-dev
  postgresql: 10
services:
  - postgresql
env:
  - ENABLE_WEB_CONSOLE='true'
  - ENABLE_WEB_CONSOLE='false'
before_script:
  - 'cp config/application.travis.yml config/application.yml'
  - "psql -c 'create database monitor_test;' -U postgres"
  - 'bundle exec rake db:migrate'
  - 'slapd -f test/fixtures/ldap/slapd.conf -h ldap://localhost:3389'
  - 'bundle exec rake ldap:reset'
