source 'https://rubygems.org'

gem 'jekyll', '~> 4.0.1'

gem 'sass'
gem 'coffee-script'
gem 'uglifier'
gem 'kramdown'
gem 'bootstrap-sass'
gem 'autoprefixer-rails'

group :jekyll_plugins do
  gem 'jekyll-assets'
  gem 'jekyll-multiple-languages-plugin'
end
